variables:
  docker: "docker -H tcp://127.0.0.1:4243"
  docker_swarm: "docker -H tcp://10.218.77.36:3376"

stages:
  - build

before_script:
  - image=reg.docker.alibaba-inc.com/aliimage:1.2.8
  - hostname -i
  - whoami

build_image:
  stage: build
  script:
    - echo $image
    - if [ "`$docker images -q $image`" ]; then $docker rmi $($docker images -q $image); fi
    - echo "Build Docker Image..."
    - $docker build --no-cache -t $image .
    - echo "Push Docker Image to repository..."  
    - $docker push $image
    - echo "Fetch Docker Image to dockeryard..."  
    - $docker_swarm pull $image
  only:
    - master
